name: Pull Request Comment Trigger Example
on:
  push:

jobs:
  run-aci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download ACI integration
        run: ./scripts/install_linux.sh

      - name: "login azure"
        run: "docker login azure --client-id $AZURE_CLIENT_ID --client-secret $AZURE_CLIENT_SECRET --tenant-id $AZURE_TENANT_ID"
        env:
          AZURE_TENANT_ID: '${{ secrets.AZURE_TENANT_ID }}'
          AZURE_CLIENT_ID: '${{ secrets.AZURE_CLIENT_ID }}'
          AZURE_CLIENT_SECRET: '${{ secrets.AZURE_CLIENT_SECRET }}'

      - name: "Create an aci context"
        run: 'docker context create aci --subscription-id $AZURE_SUBSCRIPTION_ID --resource-group gtardif --location westeurope acicontext'
        env:
          AZURE_SUBSCRIPTION_ID: '${{ secrets.AZURE_SUBSCRIPTION_ID }}'

      - name: "Run nginx"
        run: 'docker --context acicontext run -d --name nginx --domainname gtatestnginx -p 80:80 nginx '

      - name: "Test deployed server"
        run: 'curl http://gtatestnginx.westeurope.azurecontainer.io/'

      - name: "Stop Running nginx"
        run: 'docker --context acicontext rm -f nginx'
