name: Continuous integration

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Testing"

      - name: Build
        run: echo "Building"