name: Pull Request Comment Trigger Example
on:
  push:

jobs:
  run-aci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download ACI integration
        run: ./scripts/install_linux.sh

      - name: "create aci context"
        run: 'docker context create aci --help'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'